version: '3'
services:
  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
    ports:
      - 8080:80
  webapp-with-opcache:
    build:
      context: webapp
      dockerfile: Dockerfile-with-opcache
    ports:
      - 8081:80
  webapp-with-opcache-redis:
    build:
      context: webapp
      dockerfile: Dockerfile-with-opcache-redis
    links:
      - redis
    ports:
      - 8082:80
  redis:
    image: redis
